language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: smr.kyu@gmail.com
  api_key:
    secure: XfTks4951HmwbKJ4sFeDJg1G4aw9yr2IVkSW0FZTIMv96FKo1LmNoAeon5lO+BXXqqpSdKr2P/has3nDQz5QB/VJrE5b8NPxFq2OITlPTN6Zor3Py1RFq65swUuKRBOK2y0fpKGZ/PIhv/8MF21Za8OIRQR8a7hnjmfkSOfZ4rM=
  on:
    tags: true
    all_branches: true
sudo: false
